name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # Adjust this to your default branch
  pull_request:
    branches:
      - master  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master  # Specify the branch to checkout
        token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output variable
        run: echo "my_output=value" >> $GITHUB_ENV

      - name: Use output variable
        run: |
          echo "The output value is $my_output"

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10  # Specify the Ruby version you need

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
